apiVersion: v1
kind: Service
metadata:
  name: template-test-service
  finalizers: 
    - service.k8s.aws/resources
spec:
  ports:
    - name: 80-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app:  template-test
  type: LoadBalancer